In [1]:
import gymnasium as gym
gym.make('CartPole-v1')

<TimeLimit<OrderEnforcing<PassiveEnvChecker<CartPoleEnv<CartPole-v1>>>>>

In [2]:
import torch 

/root/.local/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [29]:
sprobs = torch.softmax(torch.tensor([5.0,1.,1.]), -1)
sprobs

tensor([0.9647, 0.0177, 0.0177])

In [31]:
lsprobs = torch.log_softmax(torch.tensor([5.0,1.,1.]), -1)
lsprobs

tensor([-0.0360, -4.0360, -4.0360])

In [30]:
# c = torch.distributions.Categorical(torch.tensor([5.0,1.,1.]))
c = torch.distributions.Categorical(sprobs)
c.probs

tensor([0.9647, 0.0177, 0.0177])

In [8]:
a = torch.randn((1,5))
a.detach()

tensor([[-0.3827, -0.0586,  0.0845,  0.4314,  2.2272]])